openapi: 3.1.0
info:
  title: RES Letter JSON Generator API
  version: 1.0.0
servers:
  - url: https://res-letter-api.onrender.com  # ⬅️ Replace this with your actual Render URL
paths:
  /generate_letter_json:
    post:
      operationId: generateLetterJson
      summary: Generate structured letter JSON for RES templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: |
                    A natural language prompt describing the engineering letter,
                    including site details, findings, observations, code citations, and recommendations.
      responses:
        '200':
          description: A structured JSON containing the letter fields for RES Suite
          content:
            application/json:
              schema:
                type: object
                properties:
                  letter_data:
                    type: object
                    description: JSON matching RES Suite's expected input format
